easy_admin:
    site_name: 'PROGestion'
    design:
        menu:
            - { entity: 'Vehicule', icon: 'car' }
            - { entity: 'Lot', icon: 'box' }
            - { entity: 'Avarie', icon: 'exclamation-triangle' }
            - { entity: 'Utilisateur', icon: 'users' }
        assets:
            favicon: '/favicon.ico'
    formats:
        datetime: 'd/m/Y H:i'
    routes:
        prefix: '/admin'
        format: 'html' 