framework:
    secret: '%env(APP_SECRET)%'
    annotations: false
    http_method_override: true
    handle_all_throwables: true

    session:
        handler_id: null
        cookie_secure: false  # Désactivé en local
        cookie_samesite: lax

    esi: true
    fragments: true
    php_errors:
        log: true

    trusted_proxies: ~
    trusted_hosts: ~
