security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            # Commenté temporairement
            # provider: app_user_provider
            # custom_authenticator: App\Security\UtilisateurAuthenticator
            # logout:
            #     path: app_logout
            #     target: app_login
            
            # Désactiver la sécurité temporairement
            security: false

    access_control:
        # Commenté temporairement
        # - { path: ^/login$, roles: PUBLIC_ACCESS }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/logistique, roles: ROLE_LOGISTICIEN }
        # - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
