security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            security: false
            logout:
                path: app_logout
                target: app_home

    access_control: ~
