security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/  # Pour le débogage
            security: false

        main:
            pattern: ^/
            security: false  # Désactiver temporairement la sécurité

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
