twig:
    file_name_pattern: '*.twig'
    debug: '%kernel.debug%'
    strict_variables: true
    exception_controller: null
    form_themes:
        - 'form_div_layout.html.twig'

when@test:
    twig:
        strict_variables: true
