# Désactiver toutes les routes du profiler
# web_profiler_wdt:
#     resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
#     prefix: /_wdt

# web_profiler:
#     resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
#     prefix: /_profiler 