index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: app_login

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout

app_home:
    path: /home
    controller: App\Controller\HomeController::index

admin:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index
