index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: app_login

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout

admin:
    resource: ../src/Controller/Admin/
    type: attribute
    prefix: /admin
admin_dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index
