# Routes principales
index:
    path: /
    controller: App\Controller\SecurityController::index

app_home:
    path: /home
    controller: App\Controller\HomeController::index

# Routes d'administration
admin:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index

# Routes de gestion
app_lots:
    path: /lots
    controller: App\Controller\LotController::index
    defaults:
        _locale: fr

app_avaries:
    path: /avaries
    controller: App\Controller\AvarieController::index

# Routes d'authentification
app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

